name: CI/CD for react Todo 

on:
  push:
    branches:
      - master

jobs:
  # Build Job
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
  check-code:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: install flake8
        run: |
          pip install flake8
      - name: run pep8 
        run: |
          ls
          
  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: install pytest
        run: |
          pip install pytest

      - name: Install Dependencies
        run: |
          pip install -r app/requirement.txt

      - name: Build Project
        run: |
          mkdir output
          pip install -r app/requirement.txt -t output/
          zip -r artefact.zip output/ 

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: poduction file
          path: ./artefact.zip

  # Deploy Job
  deploy:
   
    needs: [build, check-code]
    
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: poduction file
          path: ./todo/build

