name: CI/CD for react Todo 

on:
  push:
    branches:
      - master

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: install pytest
        run: |
          pip install pytest

      - name: Install Dependencies
        run: |
          pip install -r app/requirement.txt

      - name: Build Project
        run: |
          mkdir output
          pip install -r app/requirement.txt -t output/
          zip -r artefact.zip output/ 

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: poduction file
          path: ./artefact.zip

  # Deploy Job
  deploy:
   
    needs: build
    
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: poduction file
          path: ./todo/build

